export const surahs = [
  { id: 1, name: "الفاتحة", nameTr: "Fâtiha", ayahs: 7 },
  { id: 2, name: "البقرة", nameTr: "Bakara", ayahs: 286 },
  { id: 3, name: "آل عمران", nameTr: "Âl-i İmrân", ayahs: 200 },
  { id: 4, name: "النساء", nameTr: "Nisâ", ayahs: 176 },
  { id: 5, name: "المائدة", nameTr: "Mâide", ayahs: 120 },
  { id: 6, name: "الأنعام", nameTr: "En'âm", ayahs: 165 },
  { id: 7, name: "الأعراف", nameTr: "A'râf", ayahs: 206 },
  { id: 8, name: "الأنفال", nameTr: "Enfâl", ayahs: 75 },
  { id: 9, name: "التوبة", nameTr: "Tevbe", ayahs: 129 },
  { id: 10, name: "يونس", nameTr: "Yûnus", ayahs: 109 },
  { id: 11, name: "هود", nameTr: "Hûd", ayahs: 123 },
  { id: 12, name: "يوسف", nameTr: "Yûsuf", ayahs: 111 },
  { id: 13, name: "الرعد", nameTr: "Ra'd", ayahs: 43 },
  { id: 14, name: "إبراهيم", nameTr: "İbrâhîm", ayahs: 52 },
  { id: 15, name: "الحجر", nameTr: "Hicr", ayahs: 99 },
  { id: 16, name: "النحل", nameTr: "Nahl", ayahs: 128 },
  { id: 17, name: "الإسراء", nameTr: "İsrâ", ayahs: 111 },
  { id: 18, name: "الكهف", nameTr: "Kehf", ayahs: 110 },
  { id: 19, name: "مريم", nameTr: "Meryem", ayahs: 98 },
  { id: 20, name: "طه", nameTr: "Tâhâ", ayahs: 135 },
  { id: 21, name: "الأنبياء", nameTr: "Enbiyâ", ayahs: 112 },
  { id: 22, name: "الحج", nameTr: "Hacc", ayahs: 78 },
  { id: 23, name: "المؤمنون", nameTr: "Mü'minûn", ayahs: 118 },
  { id: 24, name: "النور", nameTr: "Nûr", ayahs: 64 },
  { id: 25, name: "الفرقان", nameTr: "Furkân", ayahs: 77 },
  { id: 26, name: "الشعراء", nameTr: "Şuarâ", ayahs: 227 },
  { id: 27, name: "النمل", nameTr: "Neml", ayahs: 93 },
  { id: 28, name: "القصص", nameTr: "Kasas", ayahs: 88 },
  { id: 29, name: "العنكبوت", nameTr: "Ankebût", ayahs: 69 },
  { id: 30, name: "الروم", nameTr: "Rûm", ayahs: 60 },
  { id: 31, name: "لقمان", nameTr: "Lokmân", ayahs: 34 },
  { id: 32, name: "السجدة", nameTr: "Secde", ayahs: 30 },
  { id: 33, name: "الأحزاب", nameTr: "Ahzâb", ayahs: 73 },
  { id: 34, name: "سبأ", nameTr: "Sebe'", ayahs: 54 },
  { id: 35, name: "فاطر", nameTr: "Fâtır", ayahs: 45 },
  { id: 36, name: "يس", nameTr: "Yâsîn", ayahs: 83 },
  { id: 37, name: "الصافات", nameTr: "Sâffât", ayahs: 182 },
  { id: 38, name: "ص", nameTr: "Sâd", ayahs: 88 },
  { id: 39, name: "الزمر", nameTr: "Zümer", ayahs: 75 },
  { id: 40, name: "غافر", nameTr: "Mü'min", ayahs: 85 },
  { id: 41, name: "فصلت", nameTr: "Fussilet", ayahs: 54 },
  { id: 42, name: "الشورى", nameTr: "Şûrâ", ayahs: 53 },
  { id: 43, name: "الزخرف", nameTr: "Zuhruf", ayahs: 89 },
  { id: 44, name: "الدخان", nameTr: "Duhân", ayahs: 59 },
  { id: 45, name: "الجاثية", nameTr: "Câsiye", ayahs: 37 },
  { id: 46, name: "الأحقاف", nameTr: "Ahkâf", ayahs: 35 },
  { id: 47, name: "محمد", nameTr: "Muhammed", ayahs: 38 },
  { id: 48, name: "الفتح", nameTr: "Fetih", ayahs: 29 },
  { id: 49, name: "الحجرات", nameTr: "Hucurât", ayahs: 18 },
  { id: 50, name: "ق", nameTr: "Kâf", ayahs: 45 },
  { id: 51, name: "الذاريات", nameTr: "Zâriyât", ayahs: 60 },
  { id: 52, name: "الطور", nameTr: "Tûr", ayahs: 49 },
  { id: 53, name: "النجم", nameTr: "Necm", ayahs: 62 },
  { id: 54, name: "القمر", nameTr: "Kamer", ayahs: 55 },
  { id: 55, name: "الرحمن", nameTr: "Rahman", ayahs: 78 },
  { id: 56, name: "الواقعة", nameTr: "Vâkıa", ayahs: 96 },
  { id: 57, name: "الحديد", nameTr: "Hadîd", ayahs: 29 },
  { id: 58, name: "المجادلة", nameTr: "Mücadele", ayahs: 22 },
  { id: 59, name: "الحشر", nameTr: "Haşr", ayahs: 24 },
  { id: 60, name: "الممتحنة", nameTr: "Mümtehine", ayahs: 13 },
  { id: 61, name: "الصف", nameTr: "Saff", ayahs: 14 },
  { id: 62, name: "الجمعة", nameTr: "Cuma", ayahs: 11 },
  { id: 63, name: "المنافقون", nameTr: "Münâfikûn", ayahs: 11 },
  { id: 64, name: "التغابن", nameTr: "Tegâbün", ayahs: 18 },
  { id: 65, name: "الطلاق", nameTr: "Talâk", ayahs: 12 },
  { id: 66, name: "التحريم", nameTr: "Tahrîm", ayahs: 12 },
  { id: 67, name: "الملك", nameTr: "Mülk", ayahs: 30 },
  { id: 68, name: "القلم", nameTr: "Kalem", ayahs: 52 },
  { id: 69, name: "الحاقة", nameTr: "Hâkka", ayahs: 52 },
  { id: 70, name: "المعارج", nameTr: "Meâric", ayahs: 44 },
  { id: 71, name: "نوح", nameTr: "Nûh", ayahs: 28 },
  { id: 72, name: "الجن", nameTr: "Cin", ayahs: 28 },
  { id: 73, name: "المزمل", nameTr: "Müzzemmil", ayahs: 20 },
  { id: 74, name: "المدثر", nameTr: "Müddessir", ayahs: 56 },
  { id: 75, name: "القيامة", nameTr: "Kıyâme", ayahs: 40 },
  { id: 76, name: "الإنسان", nameTr: "İnsân", ayahs: 31 },
  { id: 77, name: "المرسلات", nameTr: "Mürselât", ayahs: 50 },
  { id: 78, name: "النبأ", nameTr: "Nebe'", ayahs: 40 },
  { id: 79, name: "النازعات", nameTr: "Nâziât", ayahs: 46 },
  { id: 80, name: "عبس", nameTr: "Abese", ayahs: 42 },
  { id: 81, name: "التكوير", nameTr: "Tekvîr", ayahs: 29 },
  { id: 82, name: "الانفطار", nameTr: "İnfitâr", ayahs: 19 },
  { id: 83, name: "المطففين", nameTr: "Mutaffifîn", ayahs: 36 },
  { id: 84, name: "الانشقاق", nameTr: "İnşikâk", ayahs: 25 },
  { id: 85, name: "البروج", nameTr: "Burûc", ayahs: 22 },
  { id: 86, name: "الطارق", nameTr: "Târık", ayahs: 17 },
  { id: 87, name: "الأعلى", nameTr: "A'lâ", ayahs: 19 },
  { id: 88, name: "الغاشية", nameTr: "Gâşiye", ayahs: 26 },
  { id: 89, name: "الفجر", nameTr: "Fecr", ayahs: 30 },
  { id: 90, name: "البلد", nameTr: "Beled", ayahs: 20 },
  { id: 91, name: "الشمس", nameTr: "Şems", ayahs: 15 },
  { id: 92, name: "الليل", nameTr: "Leyl", ayahs: 21 },
  { id: 93, name: "الضحى", nameTr: "Duhâ", ayahs: 11 },
  { id: 94, name: "الشرح", nameTr: "İnşirâh", ayahs: 8 },
  { id: 95, name: "التين", nameTr: "Tîn", ayahs: 8 },
  { id: 96, name: "العلق", nameTr: "Alak", ayahs: 19 },
  { id: 97, name: "القدر", nameTr: "Kadir", ayahs: 5 },
  { id: 98, name: "البينة", nameTr: "Beyyine", ayahs: 8 },
  { id: 99, name: "الزلزلة", nameTr: "Zilzâl", ayahs: 8 },
  { id: 100, name: "العاديات", nameTr: "Âdiyât", ayahs: 11 },
  { id: 101, name: "القارعة", nameTr: "Kâria", ayahs: 11 },
  { id: 102, name: "التكاثر", nameTr: "Tekâsür", ayahs: 8 },
  { id: 103, name: "العصر", nameTr: "Asr", ayahs: 3 },
  { id: 104, name: "الهمزة", nameTr: "Hümeze", ayahs: 9 },
  { id: 105, name: "الفيل", nameTr: "Fîl", ayahs: 5 },
  { id: 106, name: "قريش", nameTr: "Kureyş", ayahs: 4 },
  { id: 107, name: "الماعون", nameTr: "Mâûn", ayahs: 7 },
  { id: 108, name: "الكوثر", nameTr: "Kevser", ayahs: 3 },
  { id: 109, name: "الكافرون", nameTr: "Kâfirûn", ayahs: 6 },
  { id: 110, name: "النصر", nameTr: "Nasr", ayahs: 3 },
  { id: 111, name: "المسد", nameTr: "Tebbet", ayahs: 5 },
  { id: 112, name: "الإخلاص", nameTr: "İhlâs", ayahs: 4 },
  { id: 113, name: "الفلق", nameTr: "Felak", ayahs: 5 },
  { id: 114, name: "الناس", nameTr: "Nâs", ayahs: 6 }
];

export const getAyahIndex = (surahId, ayahNum) => {
  let index = 0;
  for (let i = 0; i < surahId - 1; i++) {
    index += surahs[i].ayahs;
  }
  return index + ayahNum;
};

export const getSurahFromIndex = (index) => {
  let remaining = index;
  for (let i = 0; i < surahs.length; i++) {
    if (remaining <= surahs[i].ayahs) {
      return { surah: surahs[i], ayah: remaining === 0 ? 1 : remaining };
    }
    remaining -= surahs[i].ayahs;
  }
  return { surah: surahs[113], ayah: 6 };
};
